version = 0.1
[default.deploy.parameters]
stack_name = "sam-prod-lvl-monitoring"
resolve_s3 = true
s3_prefix = "sam-prod-lvl-monitoring"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
